name: homeeaseapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  logger: ^2.5.0
  cloud_firestore: ^5.5.1
  http: ^1.2.2
  geolocator: ^13.0.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/cleaning.jpg
    - assets/images/electronic_repairs.jpg
    - assets/images/plumbing.jpg
    - assets/images/appliance_repairs.jpg

