name: homeeaseapp
description: "A new Flutter project."

# Prevent accidental publication to pub.dev
publish_to: 'none'

# Application version
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  logger: ^2.5.0
  cloud_firestore: ^5.5.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
